### PR TITLE
Compile frequently-used classes

### PR DESCRIPTION
**Pull request by thewilkybarkid**
To try and reduce the amount of classes that are autoloaded, I've tried to work out which Puli classes are frequently used in production and add them to the compiled list.

I imagine that this list isn't completely optimised (eg some missing).

### CODE REVIEW

**Comment by xabbuh** [comment]
Given that this makes debugging harder and that nowadays Opcache alone should be sufficient is this really something worth to do?

**Comment by webmozart** [comment]
Good question. Any benchmarks on a recent PHP version with an opcache?

**Comment by xabbuh** [comment]
@javiereguiluz did some benchmarks for EasyAdminBundle (see javiereguiluz/EasyAdminBundle#1003). Not sure if that's helpful for you though.

**Comment by javiereguiluz** [comment]
In our case the gains were minimal. Be careful because the classes to compile can't contain neither annotations nor `__DIR__` or `__FILE__` constants, as @stof reminded me today while reviewing https://github.com/symfony/symfony-docs/pull/6405.

**Comment by webmozart** [comment]
Thanks for the feedback @javiereguiluz. I guess we can close this then.

**Pull request closed without merging**
